package com.simulation.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import com.simulation.models.privileges.PrivilegeType;

import java.util.UUID;

//================================================================================
// Client generated by god object to be served by a pay deck based
// on their privileges.
// Have a Position on the map I guess should be moved to an UI class
//================================================================================


// kapa:
// забрав сетери, щоб не можна було міняти, тільки позицію можна
// поки що лишаю таким, бо планується, що рухом займається інший клас
@AllArgsConstructor
@Getter
public class Client {
    private final String id;
    private int ticketsToBuy;
    PrivilegeType privilege;
    public Client() {
        id = UUID.randomUUID().toString();
    }

    public void interrupt() {
        privilege = PrivilegeType.Interrupted;
    }
}
