package models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import models.privileges.PrivilegeType;

//================================================================================
// Client generated by god object to be served by a pay deck based
// on their privileges.
// Have a Position on the map I guess should be moved to an UI class
//================================================================================


// kapa:
// забрав сетери, щоб не можна було міняти, тільки позицію можна
// поки що лишаю таким, бо планується, що рухом займається інший клас
@AllArgsConstructor
@Getter
public class Client {
    private final int id;
    private final int ticketsToBuy;
    PrivilegeType privilege;

    public void interrupt() {
        privilege = PrivilegeType.Interrupted;
    }
}
