package models;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import models.privileges.PrivilegeCategory;

import java.util.HashSet;
import java.util.Set;

//================================================================================
// Client generated by god object to be served by a pay deck based
// on their privileges.
// Have a Position on the map I guess should be moved to an UI class
//================================================================================

@RequiredArgsConstructor
@Getter
@Setter
public class Client {
    private final int id;
    private final String firstName;
    private final String lastName;
    private final int ticketsToBuy;
    private int priority;
    private double speed;
    private Position currPosition;
    private Set<PrivilegeCategory> privileges; // шоб не було з 2ома студентськими, а може то оке і можна зробити List

    public void addPrivilegeCategory(PrivilegeCategory privilegeCategory) {
        privileges.add(privilegeCategory);
    }
}
